# Copyright (c) 2025 Softwell Srl, Milano, Italy
# SPDX-License-Identifier: Apache-2.0

"""
sqlite_adapter.py - Concrete SQLite adapter/database pair
==========================================================

``SqliteAdapter`` wires DDL generation to :class:`SqliteWriter` and
introspection to :class:`SqliteReader`; ``SqliteDatabase`` is the
:class:`Database` facade consumers instantiate. ``sqlite3`` is in the
standard library, so no optional extra is required.

Schemas via ATTACH DATABASE
---------------------------

SQLite has no schemas: the mapping is one file per schema. Given
``connection_params = {'dbname': '/abs/path/base.db'}``, schema ``<s>``
lives in ``<dirname>/<stem>_<s>.db``. Every connection ATTACHes all the
schema files and enables foreign keys, so ``"schema"."table"`` qualified
names work natively. ``createSchemaSql`` returns the ATTACH statement (it
depends on the path, so it lives on the adapter, not the static writer).
"""

import os
import re
import sqlite3

from genro_sqlmigration.database import BaseAdapter, Database
from genro_sqlmigration.exceptions import (
    NonExistingDbException,
    SqlConnectionException,
    SqlMigrationError,
)
from genro_sqlmigration.readers import SqliteReader
from genro_sqlmigration.writers import SqliteWriter


class SqliteAdapter(BaseAdapter):
    """SQLite adapter: SqliteWriter for DDL, SqliteReader for introspection, sqlite3 for execution."""

    TYPE_CONVERSIONS = SqliteWriter.TYPE_CONVERSIONS

    def __init__(self, database):
        self.database = database
        self.writer = SqliteWriter()
        self._reader = None

    # -- Connections ---------------------------------------------------------

    def connect(self, manager=False, autocommit=False):
        """Open a sqlite3 connection, ATTACH schema files, enable foreign keys.

        ``manager`` is meaningless in SQLite (no maintenance database), so it
        is treated as False. A missing main file raises
        :class:`NonExistingDbException` (``sqlite3.connect`` would silently
        create it); any other failure raises :class:`SqlConnectionException`.
        """
        dbname = self.database.get_dbname()
        if not os.path.exists(dbname):
            raise NonExistingDbException(dbname)
        try:
            connection = sqlite3.connect(dbname)
            connection.execute('PRAGMA foreign_keys = ON')
            for schema_name, path in self.database.schema_files().items():
                connection.execute(
                    f'ATTACH DATABASE \'{path}\' AS "{schema_name}"'
                )
            return connection
        except (sqlite3.OperationalError, sqlite3.DatabaseError) as error:
            raise SqlConnectionException(dbname, original_error=error) from error

    def _connect_creating(self):
        """Open a connection, creating the main file if it does not exist."""
        dbname = self.database.get_dbname()
        connection = sqlite3.connect(dbname)
        connection.execute('PRAGMA foreign_keys = ON')
        for schema_name, path in self.database.schema_files().items():
            connection.execute(f'ATTACH DATABASE \'{path}\' AS "{schema_name}"')
        return connection

    # Matches the shared "ALTER TABLE "s"."t" ADD CONSTRAINT "n" UNIQUE (cols)"
    # statement so it can be rewritten as a UNIQUE INDEX (see execute).
    _ADD_UNIQUE_RE = re.compile(
        r'^ALTER\s+TABLE\s+"(?P<schema>[^"]+)"\."(?P<table>[^"]+)"\s+'
        r'ADD\s+CONSTRAINT\s+"(?P<name>[^"]+)"\s+UNIQUE\s*\((?P<cols>.+)\)$',
        re.IGNORECASE | re.DOTALL,
    )

    def execute(self, sql, autoCommit=False, manager=False):
        """Run a (possibly multi-statement) SQL script one statement at a time.

        Statements are split and executed sequentially on one connection
        (per-statement autocommit stance, matching the legacy behaviour).
        The connection creates the main file if missing, so a migration from
        a nonexistent database works end-to-end.
        """
        connection = self._connect_creating()
        try:
            for statement in self._split_statements(sql):
                connection.execute(statement)
            connection.commit()
        finally:
            connection.close()

    def _split_statements(self, sql):
        """Split a SQL script into executable statements, SQLite-adapting them.

        ATTACH statements (emitted by ``createSchemaSql``) are dropped: the
        connection already attaches every schema on connect, and SQLite
        rejects a second ATTACH of the same alias. ``ALTER TABLE ... ADD
        CONSTRAINT ... UNIQUE`` (generated by the shared command builder for
        a single-column UNIQUE, unsupported by SQLite's ALTER TABLE) is
        rewritten as a UNIQUE INDEX carrying the same constraint name, which
        the reader reclassifies back into the column ``unique`` attribute.
        """
        statements = []
        for raw in sql.split(';'):
            statement = raw.strip()
            if not statement:
                continue
            if statement.upper().startswith('ATTACH DATABASE'):
                continue
            statements.append(self._adapt_statement(statement))
        return statements

    def _adapt_statement(self, statement):
        """Rewrite an unsupported ADD CONSTRAINT UNIQUE into a UNIQUE INDEX."""
        match = self._ADD_UNIQUE_RE.match(statement)
        if not match:
            return statement
        return (
            f'CREATE UNIQUE INDEX "{match.group("schema")}".'
            f'"{match.group("name")}" ON "{match.group("table")}" '
            f'({match.group("cols")})'
        )

    # -- Introspection (delegated to SqliteReader) ----------------------------

    @property
    def reader(self):
        """Lazily build the SqliteReader bound to this database."""
        if self._reader is None:
            self._reader = SqliteReader(
                self.database.connection_params(),
                schemas=self.database.schema_files(),
            )
        return self._reader

    @property
    def capabilities(self):
        """Dialect capability set, declared by the writer."""
        return self.writer.CAPABILITIES

    # -- SQL generation (delegated to SqliteWriter) ---------------------------

    def createDbSql(self, dbname, encoding='UNICODE'):
        """SQLite creates the file on connect; return a harmless no-op."""
        return 'SELECT 1;'

    def createSchemaSql(self, schema_name):
        """Return the ATTACH statement for a schema (path-dependent).

        The writer's ``create_schema_sql`` cannot know the path, so schema
        creation is resolved here from ``self.database``.
        """
        path = self.database.schema_files()[schema_name]
        return f'ATTACH DATABASE \'{path}\' AS "{schema_name}";'

    def columnSqlType(self, dtype, size=None):
        return self.writer.column_sql_type(dtype, size=size)

    def columnSqlDefinition(self, column_name, dtype, size=None,
                            notnull=False, default=None,
                            extra_sql=None, generated_expression=None):
        return self.writer.column_sql_definition(
            column_name, dtype, size=size, notnull=notnull, default=default,
            extra_sql=extra_sql, generated_expression=generated_expression
        )

    def adaptSqlName(self, name):
        return f'"{name}"'

    def struct_constraint_sql(self, constraint_name, constraint_type,
                              columns=None, check_clause=None, **kwargs):
        return self.writer.constraint_sql(
            constraint_name, constraint_type,
            columns=columns, check_clause=check_clause
        )

    def struct_foreign_key_sql(self, fk_name, columns, related_table,
                               related_schema, related_columns,
                               on_delete=None, on_update=None,
                               deferrable=False, initially_deferred=False):
        return self.writer.foreign_key_sql(
            fk_name, columns, related_table, related_schema, related_columns,
            on_delete=on_delete, on_update=on_update,
            deferrable=deferrable, initially_deferred=initially_deferred
        )

    def struct_create_index_sql(self, schema_name, table_name, columns,
                                index_name=None, unique=False, method=None,
                                with_options=None, tablespace=None,
                                where=None):
        return self.writer.create_index_sql(
            schema_name, table_name, columns,
            index_name=index_name, unique=unique, method=method,
            with_options=with_options, tablespace=tablespace, where=where
        )

    def struct_create_extension_sql(self, extension_name):
        return self.writer.create_extension_sql(extension_name)

    def struct_comment_on_column_sql(self, schema_name, table_name,
                                     column_name, comment):
        return self.writer.comment_on_column_sql(
            schema_name, table_name, column_name, comment
        )

    def struct_comment_on_table_sql(self, schema_name, table_name, comment):
        return self.writer.comment_on_table_sql(schema_name, table_name, comment)

    def struct_drop_table_pkey_sql(self, schema_name, table_name):
        return self.writer.drop_table_pkey_sql(schema_name, table_name)

    def struct_add_table_pkey_sql(self, schema_name, table_name, pkeys):
        return self.writer.add_table_pkey_sql(schema_name, table_name, pkeys)

    def struct_alter_column_sql(self, column_name, new_sql_type, **kwargs):
        return self.writer.alter_column_sql(column_name, new_sql_type)

    def struct_alter_column_with_conversion_sql(self, column_name,
                                                new_sql_type,
                                                conversion_expression,
                                                **kwargs):
        return self.writer.alter_column_with_conversion_sql(
            column_name, new_sql_type, conversion_expression
        )

    def struct_add_not_null_sql(self, column_name, **kwargs):
        return self.writer.add_not_null_sql(column_name)

    def struct_drop_not_null_sql(self, column_name, **kwargs):
        return self.writer.drop_not_null_sql(column_name)

    def struct_drop_constraint_sql(self, constraint_name, **kwargs):
        return self.writer.drop_constraint_sql(constraint_name)

    def struct_add_column_sql(self, column_definition):
        return self.writer.add_column_sql(column_definition)

    def struct_alter_table_commands(self, schema_name, table_name,
                                    column_fragments):
        return self.writer.alter_table_commands(
            schema_name, table_name, column_fragments
        )


class SqliteDatabase(Database):
    """Production SQLite database facade.

    Consumers pass ``connection_params = {'dbname': '/abs/path/base.db'}``
    and the schema lists; schema ``<s>`` maps to ``<dir>/<stem>_<s>.db``.
    """

    def __init__(self, connection_params, application_schemas=None,
                 read_only_schemas=None, tenant_schemas=None):
        self._connection_params = dict(connection_params)
        if 'dbname' not in self._connection_params:
            raise SqlMigrationError("connection_params must include 'dbname'")
        self._application_schemas = list(application_schemas or [])
        self._read_only_schemas = list(read_only_schemas or [])
        self._tenant_schemas = list(tenant_schemas or [])
        self._adapter = SqliteAdapter(self)
        self._connection = None

    @property
    def adapter(self):
        return self._adapter

    def get_dbname(self):
        return self._connection_params['dbname']

    def connection_params(self, manager=False):
        """Connection kwargs; ``manager`` is meaningless in SQLite."""
        return dict(self._connection_params)

    def schema_files(self):
        """Map every known schema to its ``<dir>/<stem>_<schema>.db`` file."""
        dbname = self.get_dbname()
        directory = os.path.dirname(dbname)
        stem = os.path.splitext(os.path.basename(dbname))[0]
        schemas = self._application_schemas + self._read_only_schemas + self._tenant_schemas
        return {
            schema_name: os.path.join(directory, f'{stem}_{schema_name}.db')
            for schema_name in schemas
        }

    # -- Schemas seen by the migrator -----------------------------------------

    def getApplicationSchemas(self):
        return self._application_schemas

    def readOnlySchemas(self):
        return self._read_only_schemas

    def getTenantSchemas(self):
        return self._tenant_schemas

    # -- Persistent connection ------------------------------------------------

    def startup(self):
        """Open the persistent connection lazily (legacy ``db.startup()``)."""
        if self._connection is None:
            self._connection = self._adapter.connect()

    def execute(self, sql):
        self.startup()
        return self._connection.execute(sql)

    def commit(self):
        if self._connection is not None:
            self._connection.commit()

    def closeConnection(self):
        if self._connection is not None:
            self._connection.close()
        self._connection = None
